version: '3.8'

services:
  app:
    container_name: epam-general-gpt
    build: .
    image: epam-general-gpt:1.0
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
