version: '3.8'

services:
  app:
    container_name: gpt-finance-frontend
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped